---
- name: Setup Docker and user on Ubuntu 22.04
  hosts: all
  become: yes

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Create a new user called 'devops'
      user:
        name: devops
        state: present
        create_home: yes

    - name: Add 'devops' user to the 'docker' group
      user:
        name: devops
        groups: docker
        append: yes